# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activesupport'
gem 'pg'
gem 'pry'
gem 'bcrypt'

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'